import fs from 'fs';
let content = fs.readFileSync('src/App.tsx', 'utf8');

const oldZettelkasten = `        ) : activeFeature === 'zettelkasten' ? (\n           <Suspense fallback={<div className="flex-1 flex items-center justify-center text-zinc-500"><Loader2 className="w-8 h-8 animate-spin" /></div>}>\n             <ZettelkastenGraph />\n           </Suspense>\n        ) : activeFeature === 'compilation' ? (\n           <Suspense fallback={<div className="flex-1 flex items-center justify-center text-zinc-500"><Loader2 className="w-8 h-8 animate-spin" /></div>}>\n             <CompilationBoard />\n           </Suspense>\n        ) : (`;

const newZettelkasten = `        ) : activeFeature === 'zettelkasten' || activeFeature === 'compilation' ? (\n           <div className="flex-1 flex flex-col w-full h-full relative">\n             <div className="absolute top-4 left-1/2 -translate-x-1/2 z-50 flex items-center p-1 bg-[#1a1a1c] border border-white/10 rounded-full shadow-2xl">\n                <button \n                  onClick={() => setActiveFeature('zettelkasten')} \n                  className={\`px-6 py-2 rounded-full text-xs font-semibold transition-all \${activeFeature === 'zettelkasten' ? 'bg-zinc-100 text-black shadow-md' : 'text-zinc-500 hover:text-white'}\`}\n                >\n                  Neural Graph\n                </button>\n                <button \n                  onClick={() => setActiveFeature('compilation')} \n                  className={\`px-6 py-2 rounded-full text-xs font-semibold transition-all \${activeFeature === 'compilation' ? 'bg-zinc-100 text-black shadow-md' : 'text-zinc-500 hover:text-white'}\`}\n                >\n                  Papan Draf\n                </button>\n             </div>\n             <Suspense fallback={<div className="flex-1 flex items-center justify-center text-zinc-500"><Loader2 className="w-8 h-8 animate-spin" /></div>}>\n               {activeFeature === 'zettelkasten' ? <ZettelkastenGraph /> : <CompilationBoard />}\n             </Suspense>\n           </div>\n        ) : (`;

content = content.replace(oldZettelkasten, newZettelkasten);
fs.writeFileSync('src/App.tsx', content);
